In [1]:
import pandas as pd
import numpy as np

In [2]:
news_data=pd.read_csv('all_news_data.csv',encoding='utf-8',index_col=0)
news_data

일자                                                키워드  \
뉴스 식별자                                                                        
4.101008e+06  2009-01-01  선물,옵션,거래,규모,사상,최대,18.3%,선물,옵션,거래,대금,18.3%,최대,경...   
1.100301e+06  2009-01-01  성장,1.9%,회복,시점,2010년,대응,정치,경제,위기,70.0%,93.0%,정비...   
1.100301e+06  2009-01-01  키코,효력,정지,판결,은행,비상,판결,은행,자본,시장,발전,저해,피해,기업,유동,위...   
2.100201e+06  2009-01-01  PB,재테크,고수,세계,금융위기,자산가치,급락,투자자,새해,자신,포트폴리오,재점검,...   
2.100201e+06  2009-01-01  PB,재테크,고수,중국,일본펀드,프라이빗뱅커,PB,가입,중국펀드,인내심,보유,단기적...   
...                  ...                                                ...   
2.100601e+06  2025-06-30  코스피,7%,초반,두산에너빌리티,코스피,코스닥,지수,미국발,훈풍,강세,초반,미국,증...   
2.100201e+06  2025-06-30  외국인,팔자,상승,출발,코스피,3080선,코스피,기관,매수세,상승,출발,돌파,눈앞,...   
1.100751e+06  2025-06-30  대한항공,서프라이즈,실적,전망,화물,부담,아시아투데이,박주연,iM투자증권,대한항공,...   
4.100078e+06  2025-06-30  LS,ELECTRIC,정부,정책,AI,육성,수혜,360,000원,NH투자증권,로보뉴...   
2.100851e+06  2025-06-30  수출,위축,전망,리스크,무협,수출산업경기전망지수,수출산업,경기,전망,지수,EBSI,...   

                                              특성추출(가중치순 상위 50개)  \
뉴스 식별자                                                            
4.101008e+06  거래량,일평균,코스피,만큼,경신,코스피200옵션,거래소,주식선물,변동성,사상최대,거...   
1.100301e+06  전문가,경제위기,국정운영,정치권,성장률,긍정평가층,경제전문가,경제회복,부정평가층,이...   
1.100301e+06             키코,중소기업,신의칙,모나미,은행권,은행들,디에스엘시디,제일은행,1조   
2.100201e+06  pb,팀장,국민은행,우리은행,한국씨티은행,상반기,투자상품,투자전략,유동성,수익률,주...   
2.100201e+06  부동산,중국,팀장,일본,외환은행,지점장,국민은행,우리은행,한국씨티은행,부양책,부동산...   
...                                                         ...   
2.100601e+06  코스피,코스닥,두산에너빌리티,미국,기대감,거래일,외국인,2만,3070선,순매도,교역...   
2.100201e+06  거래일,강보합세,약보합,코스피,외국인,거래소,코스닥,약보합세,순매도,업비트,2차,서...   
1.100751e+06          대한항공,연구원,배세호,물동량,목표주가,박주연,아시아투데이,유류비,인천공항   
4.100078e+06          ls,nh투자증권,증권사,6개월,컨센서스,상향조정,미국,nh,이민재,변압기   
2.100851e+06  반도체,자동차,복수응답,수출산업경기전망지수,ebsi,만큼,연구원,수입규제,미국발,체...   

                                                             본문  
뉴스 식별자                                                           
4.101008e+06  [이데일리 유환구기자] 글로벌 금융위기에 따라 주식시장의 변동성이 크게 확대되면서 ...  
1.100301e+06  정치권 경제위기 대응 ‘잘못한다’ 93.0% 4대강 정비 반대 70.0%,\n미국 ...  
1.100301e+06  은행권 “자본시장 발전 저해 판결”  줄소송 이어질듯피해기업 유동성 위기 모면  은...  
2.100201e+06  지난해 전세계를 뒤덮은 금융위기로 자산가치가 급락하면서 잠을 설친 투자자가 많았다....  
2.100201e+06  ◇중국 일본펀드 '어떻게 할까'＝ 프라이빗뱅커(PB)들은 이미 가입한 중국펀드는 인...  
...                                                         ...  
2.100601e+06  코스피와 코스닥 지수가 미국발(發) 훈풍에 힘입어 장 초반 강세를 보이고 있다. 앞...  
2.100201e+06  [머니투데이 박수현 기자] [개장 시황]\n\n 코스피가 기관의 매수세에 상승 출발...  
1.100751e+06  아시아투데이 박주연 기자 = iM투자증권은 30일 대한항공에 대해 분기 실적이 시장...  
4.100078e+06  [서울=뉴스핌] 로보뉴스 = NH투자증권에서 30일 LS ELECTRIC(01012...  
2.100851e+06  [자료=무협] \n한국 수출 체감경기가 3분기에도 둔화될 것이란 전망이 나왔다. 미...  

[799073 rows x 4 columns]

In [3]:
news_data['일자']=pd.to_datetime(news_data['일자'])

In [4]:
from collections import Counter
from sklearn.feature_extraction.text import TfidfVectorizer

In [5]:
df=pd.DataFrame({'date':news_data['일자'],'keywords':news_data['키워드']})

In [6]:
df['keyword_list']=df['keywords'].apply(lambda x: x.split(','))

In [7]:
# all_keywords=sum(df['keyword_list'],[])

In [8]:
from tqdm import tqdm

all_keywords = []
for keywords in tqdm(df['keyword_list']):
    all_keywords.extend(keywords)

100%|███████████████████████████████████████████████████████████████████████| 799073/799073 [00:08<00:00, 98268.29it/s]


In [9]:
top1000=[kw for kw, _ in Counter(all_keywords).most_common(80)]

In [10]:
daily_keywords=df.groupby('date')['keyword_list'].apply(lambda lists: ' '.join(sum(lists, []))).reset_index()

In [11]:
vectorizer=TfidfVectorizer(vocabulary=top1000)

In [12]:
# pd.DataFrame({'top1000':top1000}).to_csv('top1000.csv')

In [13]:
tfidf_matrix=vectorizer.fit_transform(daily_keywords['keyword_list'])

In [14]:
terms=vectorizer.get_feature_names_out()
tfidf_df=pd.DataFrame(tfidf_matrix.toarray(),columns=terms)
tfidf_df['date']=daily_keywords['date']

In [15]:
top_keywords_per_day=[]
for i, row in tfidf_df.drop(columns='date').iterrows():
    top_terms=row.sort_values(ascending=False).head(10)
    for term, score in top_terms.items():
        top_keywords_per_day.append({
            'date': tfidf_df.loc[i, 'date'],
            'keyword': term,
            'tfidf': round(score,4)
        })

In [16]:
top_df=pd.DataFrame(top_keywords_per_day)

In [17]:
top_df.sort_values(by='tfidf',ascending=False)

date keyword   tfidf
43990 2021-01-17      기업  0.8397
41950 2020-06-27      기업  0.8343
38520 2019-07-20      일본  0.8202
31390 2017-08-06      달러  0.8156
45040 2021-05-02      금융  0.8102
...          ...     ...     ...
43996 2021-01-17      상황  0.0742
39999 2019-12-14      확대  0.0680
43997 2021-01-17     가능성  0.0600
43998 2021-01-17      환율  0.0568
43999 2021-01-17      주식  0.0547

[60250 rows x 3 columns]

In [18]:
top_df

date keyword   tfidf
0     2009-01-01      경제  0.4621
1     2009-01-01      위기  0.2905
2     2009-01-01      전망  0.2574
3     2009-01-01      환율  0.2424
4     2009-01-01      정부  0.2350
...          ...     ...     ...
60245 2025-06-30      미국  0.2466
60246 2025-06-30      달러  0.2202
60247 2025-06-30      경기  0.2113
60248 2025-06-30      시장  0.1773
60249 2025-06-30      지수  0.1711

[60250 rows x 3 columns]

In [19]:
tfidf_df['날짜']=pd.to_datetime(tfidf_df['date'])
tfidf_df=tfidf_df.drop('date',axis=1)

In [20]:
tfidf_df.to_csv('top500_tfidf.csv')

In [21]:
ex_rate=pd.read_csv('./data/원화의 대미달러, 원화의 대위안_대엔 환율_10093253.csv')[['날짜','원/달러(종가 15:30)']]

In [22]:
ex_rate['날짜']=pd.to_datetime(ex_rate['날짜'])
ex_rate['원/달러(종가 15:30)']=ex_rate['원/달러(종가 15:30)'].str.replace(',','').astype(float)

In [23]:
merged_data=pd.merge(tfidf_df,ex_rate,on='날짜',how='inner')

In [24]:
merged_data['변화율']=merged_data['원/달러(종가 15:30)'].pct_change().shift(-1)
merged_data['상승']=(merged_data['변화율']>0).astype(int)

C:\Users\campus4D044\AppData\Local\Temp\ipykernel_4648\2563095799.py:1: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  merged_data['변화율']=merged_data['원/달러(종가 15:30)'].pct_change().shift(-1)


In [25]:
merged_data['원/달러 shift-1']=merged_data['원/달러(종가 15:30)'].shift(-1)
merged_data['차이']=merged_data['원/달러 shift-1']-merged_data['원/달러(종가 15:30)']
merged_data=merged_data[(merged_data['차이']>=5)|(merged_data['차이']<=-5)]

In [26]:
x=merged_data.drop(['날짜','상승','원/달러(종가 15:30)','변화율','원/달러 shift-1','차이'],axis=1) #
y=merged_data[['상승']]

In [27]:
merged_data=merged_data.dropna()

In [28]:
from sklearn.model_selection import train_test_split

In [621]:
tr_x,tt_x,tr_y,tt_y=train_test_split(x,y,train_size=0.7,shuffle=False,random_state=10)

In [622]:
from sklearn.preprocessing import StandardScaler

In [623]:
ss=StandardScaler()
tr_x=ss.fit_transform(tr_x)
tt_x=ss.transform(tt_x)

In [624]:
from sklearn.ensemble import RandomForestClassifier

In [625]:
model=RandomForestClassifier().fit(tr_x,tr_y)

C:\Users\campus4D044\anaconda3\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


In [626]:
pred_y=model.predict(tt_x)

In [627]:
from sklearn.metrics import accuracy_score,f1_score,confusion_matrix

In [628]:
print(accuracy_score(tt_y,pred_y))
print(f1_score(tt_y,pred_y))
print(confusion_matrix(tt_y,pred_y))

0.4894957983193277
0.5335892514395394
[[ 94 128]
 [115 139]]


In [629]:
from xgboost import XGBClassifier

In [630]:
model=XGBClassifier(random_state=10).fit(tr_x,tr_y)

In [631]:
pred_y=model.predict(tt_x)

In [632]:
print(accuracy_score(tt_y,pred_y))
print(f1_score(tt_y,pred_y))

0.5021008403361344
0.5306930693069307


In [633]:
from lightgbm import LGBMClassifier

In [634]:
model=LGBMClassifier(random_state=10).fit(tr_x,tr_y)

[LightGBM] [Info] Number of positive: 550, number of negative: 560
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000899 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 20145
[LightGBM] [Info] Number of data points in the train set: 1110, number of used features: 79
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.495495 -> initscore=-0.018019
[LightGBM] [Info] Start training from score -0.018019


C:\Users\campus4D044\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:97: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\campus4D044\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


In [635]:
pred_y=model.predict(tt_x)

In [636]:
print(accuracy_score(tt_y,pred_y))
print(f1_score(tt_y,pred_y))

0.5042016806722689
0.5298804780876494


In [637]:
from catboost import CatBoostClassifier

In [638]:
model=CatBoostClassifier().fit(tr_x,tr_y)

Learning rate set to 0.010772
0:	learn: 0.6923488	total: 17.6ms	remaining: 17.6s
1:	learn: 0.6915940	total: 25.5ms	remaining: 12.7s
2:	learn: 0.6908349	total: 33.6ms	remaining: 11.2s
3:	learn: 0.6902073	total: 41.8ms	remaining: 10.4s
4:	learn: 0.6893677	total: 50.2ms	remaining: 9.99s
5:	learn: 0.6887526	total: 59.9ms	remaining: 9.92s
6:	learn: 0.6880436	total: 69.7ms	remaining: 9.88s
7:	learn: 0.6875184	total: 78.8ms	remaining: 9.77s
8:	learn: 0.6870762	total: 88.1ms	remaining: 9.71s
9:	learn: 0.6861649	total: 97.3ms	remaining: 9.63s
10:	learn: 0.6854377	total: 106ms	remaining: 9.53s
11:	learn: 0.6845966	total: 115ms	remaining: 9.44s
12:	learn: 0.6839261	total: 123ms	remaining: 9.36s
13:	learn: 0.6830423	total: 132ms	remaining: 9.28s
14:	learn: 0.6824398	total: 141ms	remaining: 9.24s
15:	learn: 0.6819077	total: 151ms	remaining: 9.29s
16:	learn: 0.6812387	total: 159ms	remaining: 9.22s
17:	learn: 0.6807076	total: 168ms	remaining: 9.16s
18:	learn: 0.6799033	total: 176ms	remaining: 9.09s
1

In [639]:
pred_y=model.predict(tt_x)

In [640]:
print(accuracy_score(tt_y,pred_y))
print(f1_score(tt_y,pred_y))

0.5462184873949579
0.5985130111524164


In [539]:
from pytorch_tabnet.tab_model import TabNetClassifier

In [540]:
from  pytorch_tabnet.augmentations import ClassificationSMOTE

In [513]:
aug=ClassificationSMOTE(p=0.2)

In [514]:
model=TabNetClassifier()
model.fit(tr_x.values,tr_y.values.ravel(),max_epochs=100)

C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\abstract_model.py:82: UserWarning: Device used : cpu
  warnings.warn(f"Device used : {self.device}")
C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\abstract_model.py:687: UserWarning: No early stopping will be performed, last training weights will be used.
  warnings.warn(wrn_msg)


epoch 0  | loss: 0.97395 |  0:00:00s
epoch 1  | loss: 0.82136 |  0:00:00s
epoch 2  | loss: 0.76074 |  0:00:00s
epoch 3  | loss: 0.74768 |  0:00:00s
epoch 4  | loss: 0.73154 |  0:00:00s
epoch 5  | loss: 0.71881 |  0:00:00s
epoch 6  | loss: 0.71387 |  0:00:00s
epoch 7  | loss: 0.70044 |  0:00:00s
epoch 8  | loss: 0.70372 |  0:00:00s
epoch 9  | loss: 0.70035 |  0:00:01s
epoch 10 | loss: 0.69078 |  0:00:01s
epoch 11 | loss: 0.69821 |  0:00:01s
epoch 12 | loss: 0.69397 |  0:00:01s
epoch 13 | loss: 0.69403 |  0:00:01s
epoch 14 | loss: 0.69421 |  0:00:01s
epoch 15 | loss: 0.6933  |  0:00:01s
epoch 16 | loss: 0.69116 |  0:00:01s
epoch 17 | loss: 0.69143 |  0:00:01s
epoch 18 | loss: 0.69185 |  0:00:01s
epoch 19 | loss: 0.6922  |  0:00:02s
epoch 20 | loss: 0.69098 |  0:00:02s
epoch 21 | loss: 0.69202 |  0:00:02s
epoch 22 | loss: 0.6891  |  0:00:02s
epoch 23 | loss: 0.69387 |  0:00:02s
epoch 24 | loss: 0.69033 |  0:00:02s
epoch 25 | loss: 0.69322 |  0:00:02s
epoch 26 | loss: 0.68731 |  0:00:02s
e

In [515]:
pred_y=model.predict(tt_x.values)

In [516]:
print(accuracy_score(tt_y,pred_y))
print(f1_score(tt_y,pred_y))
print(confusion_matrix(tt_y,pred_y))

0.47471451876019577
0.34949494949494947
[[409 182]
 [462 173]]


In [210]:
np.unique(tr_y.values.ravel())

array([0, 1])

In [205]:
tr_x.values

array([[0.46348647, 0.26578108, 0.22390801, ..., 0.00636002, 0.00698272,
        0.00433177],
       [0.37973063, 0.41224756, 0.22718923, ..., 0.00749475, 0.00580219,
        0.00370226],
       [0.36544294, 0.42761299, 0.14126826, ..., 0.00175639, 0.00795446,
        0.02161821],
       ...,
       [0.2960815 , 0.24928465, 0.16533961, ..., 0.01739645, 0.        ,
        0.00310321],
       [0.26063559, 0.47367834, 0.15919319, ..., 0.        , 0.        ,
        0.03253022],
       [0.31672158, 0.30343968, 0.18069511, ..., 0.00786303, 0.00263783,
        0.        ]])

In [134]:
import optuna

In [139]:
# Optuna 최적화 함수 정의
def objective(trial):
    params = {
        "n_d": trial.suggest_int("n_d", 8, 64),
        "n_a": trial.suggest_int("n_a", 8, 64),
        "n_steps": trial.suggest_int("n_steps", 3, 10),
        "gamma": trial.suggest_float("gamma", 1.0, 2.0),
        "lambda_sparse": trial.suggest_float("lambda_sparse", 1e-5, 1e-1, log=True),
        "optimizer_params": dict(
            lr=trial.suggest_float("lr", 1e-3, 2e-2, log=True)
        ),
        "mask_type": trial.suggest_categorical("mask_type", ["entmax", "sparsemax"]),
        "seed": 42,
        "verbose": 0
    }

    clf = TabNetClassifier(**params)

    clf.fit(
        X_train=tr_x.values, y_train=tr_y.values.ravel(),
        eval_set=[(tt_x.values, tt_y.values.ravel())],
        eval_metric=["accuracy"],
        patience=10,
        max_epochs=100,
        batch_size=256,
        virtual_batch_size=128
    )

    preds = clf.predict(tt_x.values)
    acc = accuracy_score(tt_y, preds)
    return acc

# Optuna 스터디 실행
study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=30)

print("Best params:", study.best_params)
print("Best accuracy:", study.best_value)

[I 2025-07-17 10:05:02,254] A new study created in memory with name: no-name-edfac567-9a9c-41ea-8d68-76aa9c00d6ac



Early stopping occurred at epoch 22 with best_epoch = 12 and best_val_0_accuracy = 0.52252


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:05:11,385] Trial 0 finished with value: 0.5225225225225225 and parameters: {'n_d': 39, 'n_a': 37, 'n_steps': 3, 'gamma': 1.8399762973722467, 'lambda_sparse': 0.020438482401053875, 'lr': 0.01786771109097322, 'mask_type': 'entmax'}. Best is trial 0 with value: 0.5225225225225225.



Early stopping occurred at epoch 10 with best_epoch = 0 and best_val_0_accuracy = 0.51761


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:05:17,471] Trial 1 finished with value: 0.5176085176085176 and parameters: {'n_d': 43, 'n_a': 42, 'n_steps': 4, 'gamma': 1.684012253413632, 'lambda_sparse': 1.0288199104002056e-05, 'lr': 0.006116188672110791, 'mask_type': 'sparsemax'}. Best is trial 0 with value: 0.5225225225225225.



Early stopping occurred at epoch 15 with best_epoch = 5 and best_val_0_accuracy = 0.52334


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:05:32,705] Trial 2 finished with value: 0.5233415233415234 and parameters: {'n_d': 27, 'n_a': 11, 'n_steps': 9, 'gamma': 1.7529118902577774, 'lambda_sparse': 0.0005487509619416714, 'lr': 0.008938043851777905, 'mask_type': 'sparsemax'}. Best is trial 2 with value: 0.5233415233415234.



Early stopping occurred at epoch 10 with best_epoch = 0 and best_val_0_accuracy = 0.48321


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:05:43,648] Trial 3 finished with value: 0.4832104832104832 and parameters: {'n_d': 14, 'n_a': 22, 'n_steps': 9, 'gamma': 1.6451680863173777, 'lambda_sparse': 0.0007450405458687924, 'lr': 0.003258236333663476, 'mask_type': 'sparsemax'}. Best is trial 2 with value: 0.5233415233415234.



Early stopping occurred at epoch 10 with best_epoch = 0 and best_val_0_accuracy = 0.51761


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:05:52,818] Trial 4 finished with value: 0.5176085176085176 and parameters: {'n_d': 22, 'n_a': 18, 'n_steps': 7, 'gamma': 1.7566058378592384, 'lambda_sparse': 0.0004621461535099022, 'lr': 0.0014369099953382238, 'mask_type': 'sparsemax'}. Best is trial 2 with value: 0.5233415233415234.



Early stopping occurred at epoch 10 with best_epoch = 0 and best_val_0_accuracy = 0.49386


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:06:00,423] Trial 5 finished with value: 0.49385749385749383 and parameters: {'n_d': 23, 'n_a': 9, 'n_steps': 6, 'gamma': 1.3237912837304235, 'lambda_sparse': 5.249022845962296e-05, 'lr': 0.0017242484038659128, 'mask_type': 'sparsemax'}. Best is trial 2 with value: 0.5233415233415234.



Early stopping occurred at epoch 20 with best_epoch = 10 and best_val_0_accuracy = 0.51843


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:06:25,947] Trial 6 finished with value: 0.5184275184275184 and parameters: {'n_d': 46, 'n_a': 29, 'n_steps': 10, 'gamma': 1.8287195708274717, 'lambda_sparse': 0.07097795884325676, 'lr': 0.019933140604981216, 'mask_type': 'entmax'}. Best is trial 2 with value: 0.5233415233415234.



Early stopping occurred at epoch 37 with best_epoch = 27 and best_val_0_accuracy = 0.53235


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:07:07,199] Trial 7 finished with value: 0.5323505323505323 and parameters: {'n_d': 59, 'n_a': 16, 'n_steps': 9, 'gamma': 1.5043169412936055, 'lambda_sparse': 0.0006708648878675918, 'lr': 0.0024215804640121967, 'mask_type': 'sparsemax'}. Best is trial 7 with value: 0.5323505323505323.



Early stopping occurred at epoch 16 with best_epoch = 6 and best_val_0_accuracy = 0.48976


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:07:23,837] Trial 8 finished with value: 0.48976248976248976 and parameters: {'n_d': 54, 'n_a': 27, 'n_steps': 8, 'gamma': 1.9968427586101822, 'lambda_sparse': 0.000969759950447926, 'lr': 0.0020411283296331395, 'mask_type': 'sparsemax'}. Best is trial 7 with value: 0.5323505323505323.



Early stopping occurred at epoch 10 with best_epoch = 0 and best_val_0_accuracy = 0.48239


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:07:36,593] Trial 9 finished with value: 0.4823914823914824 and parameters: {'n_d': 19, 'n_a': 36, 'n_steps': 10, 'gamma': 1.4184711970609063, 'lambda_sparse': 0.010776206682290266, 'lr': 0.0028167588144128635, 'mask_type': 'entmax'}. Best is trial 7 with value: 0.5323505323505323.



Early stopping occurred at epoch 15 with best_epoch = 5 and best_val_0_accuracy = 0.5217


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:07:50,296] Trial 10 finished with value: 0.5217035217035217 and parameters: {'n_d': 63, 'n_a': 54, 'n_steps': 6, 'gamma': 1.01743242915833, 'lambda_sparse': 0.0001055906054825676, 'lr': 0.005281576521682351, 'mask_type': 'entmax'}. Best is trial 7 with value: 0.5323505323505323.



Early stopping occurred at epoch 11 with best_epoch = 1 and best_val_0_accuracy = 0.50696


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:08:00,940] Trial 11 finished with value: 0.506961506961507 and parameters: {'n_d': 32, 'n_a': 9, 'n_steps': 8, 'gamma': 1.5621434596534098, 'lambda_sparse': 0.003999914834768935, 'lr': 0.00949896135918368, 'mask_type': 'sparsemax'}. Best is trial 7 with value: 0.5323505323505323.



Early stopping occurred at epoch 20 with best_epoch = 10 and best_val_0_accuracy = 0.52088


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:08:21,511] Trial 12 finished with value: 0.5208845208845209 and parameters: {'n_d': 31, 'n_a': 14, 'n_steps': 9, 'gamma': 1.3156790172269464, 'lambda_sparse': 0.00016165468804034424, 'lr': 0.008473255863508554, 'mask_type': 'sparsemax'}. Best is trial 7 with value: 0.5323505323505323.



Early stopping occurred at epoch 10 with best_epoch = 0 and best_val_0_accuracy = 0.48649


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:08:34,145] Trial 13 finished with value: 0.4864864864864865 and parameters: {'n_d': 54, 'n_a': 55, 'n_steps': 8, 'gamma': 1.511662978573668, 'lambda_sparse': 0.003596521051059995, 'lr': 0.0010881992646277132, 'mask_type': 'sparsemax'}. Best is trial 7 with value: 0.5323505323505323.



Early stopping occurred at epoch 16 with best_epoch = 6 and best_val_0_accuracy = 0.51761


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:08:57,218] Trial 14 finished with value: 0.5176085176085176 and parameters: {'n_d': 64, 'n_a': 20, 'n_steps': 10, 'gamma': 1.1393324979324304, 'lambda_sparse': 0.00029252482007913655, 'lr': 0.011560028420781611, 'mask_type': 'sparsemax'}. Best is trial 7 with value: 0.5323505323505323.



Early stopping occurred at epoch 10 with best_epoch = 0 and best_val_0_accuracy = 0.48239


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:09:05,510] Trial 15 finished with value: 0.4823914823914824 and parameters: {'n_d': 29, 'n_a': 63, 'n_steps': 5, 'gamma': 1.9904403728096445, 'lambda_sparse': 0.0025092517546748973, 'lr': 0.0036612533731029393, 'mask_type': 'sparsemax'}. Best is trial 7 with value: 0.5323505323505323.



Early stopping occurred at epoch 10 with best_epoch = 0 and best_val_0_accuracy = 0.48239


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:09:14,086] Trial 16 finished with value: 0.4823914823914824 and parameters: {'n_d': 8, 'n_a': 15, 'n_steps': 7, 'gamma': 1.3943274462746416, 'lambda_sparse': 4.64983998588102e-05, 'lr': 0.00718057855685694, 'mask_type': 'sparsemax'}. Best is trial 7 with value: 0.5323505323505323.



Early stopping occurred at epoch 14 with best_epoch = 4 and best_val_0_accuracy = 0.48403


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:09:31,973] Trial 17 finished with value: 0.48402948402948404 and parameters: {'n_d': 50, 'n_a': 25, 'n_steps': 9, 'gamma': 1.5863753996880894, 'lambda_sparse': 0.0016977931152411668, 'lr': 0.004446546926154269, 'mask_type': 'sparsemax'}. Best is trial 7 with value: 0.5323505323505323.



Early stopping occurred at epoch 13 with best_epoch = 3 and best_val_0_accuracy = 0.51761


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:09:45,900] Trial 18 finished with value: 0.5176085176085176 and parameters: {'n_d': 39, 'n_a': 8, 'n_steps': 9, 'gamma': 1.212117832905474, 'lambda_sparse': 2.272761266762083e-05, 'lr': 0.012814631556923358, 'mask_type': 'entmax'}. Best is trial 7 with value: 0.5323505323505323.



Early stopping occurred at epoch 23 with best_epoch = 13 and best_val_0_accuracy = 0.4914


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:10:09,731] Trial 19 finished with value: 0.4914004914004914 and parameters: {'n_d': 58, 'n_a': 31, 'n_steps': 8, 'gamma': 1.7629189318144916, 'lambda_sparse': 0.00029904735818071104, 'lr': 0.00234249757250974, 'mask_type': 'sparsemax'}. Best is trial 7 with value: 0.5323505323505323.



Early stopping occurred at epoch 10 with best_epoch = 0 and best_val_0_accuracy = 0.51761


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:10:18,774] Trial 20 finished with value: 0.5176085176085176 and parameters: {'n_d': 27, 'n_a': 45, 'n_steps': 7, 'gamma': 1.4390117560516338, 'lambda_sparse': 0.012351028372547918, 'lr': 0.004723799783953593, 'mask_type': 'sparsemax'}. Best is trial 7 with value: 0.5323505323505323.



Early stopping occurred at epoch 10 with best_epoch = 0 and best_val_0_accuracy = 0.51761


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:10:23,542] Trial 21 finished with value: 0.5176085176085176 and parameters: {'n_d': 38, 'n_a': 39, 'n_steps': 3, 'gamma': 1.8716283040820136, 'lambda_sparse': 0.06743952994983071, 'lr': 0.014613600563999428, 'mask_type': 'entmax'}. Best is trial 7 with value: 0.5323505323505323.



Early stopping occurred at epoch 13 with best_epoch = 3 and best_val_0_accuracy = 0.51925


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:10:31,446] Trial 22 finished with value: 0.5192465192465192 and parameters: {'n_d': 41, 'n_a': 49, 'n_steps': 4, 'gamma': 1.8778920907864036, 'lambda_sparse': 0.017342255066875468, 'lr': 0.019296961617829216, 'mask_type': 'entmax'}. Best is trial 7 with value: 0.5323505323505323.



Early stopping occurred at epoch 28 with best_epoch = 18 and best_val_0_accuracy = 0.54218


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:10:42,575] Trial 23 finished with value: 0.5421785421785422 and parameters: {'n_d': 35, 'n_a': 32, 'n_steps': 3, 'gamma': 1.7029645287311754, 'lambda_sparse': 0.0013760855886573039, 'lr': 0.013960560634170088, 'mask_type': 'entmax'}. Best is trial 23 with value: 0.5421785421785422.



Early stopping occurred at epoch 18 with best_epoch = 8 and best_val_0_accuracy = 0.48321


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:10:53,721] Trial 24 finished with value: 0.4832104832104832 and parameters: {'n_d': 34, 'n_a': 15, 'n_steps': 5, 'gamma': 1.6765218180704706, 'lambda_sparse': 0.00161784726784942, 'lr': 0.009804660503514223, 'mask_type': 'entmax'}. Best is trial 23 with value: 0.5421785421785422.



Early stopping occurred at epoch 19 with best_epoch = 9 and best_val_0_accuracy = 0.52989


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:11:06,961] Trial 25 finished with value: 0.5298935298935299 and parameters: {'n_d': 46, 'n_a': 31, 'n_steps': 5, 'gamma': 1.5899989745318721, 'lambda_sparse': 0.0005502116239597578, 'lr': 0.0066016117768050485, 'mask_type': 'entmax'}. Best is trial 23 with value: 0.5421785421785422.



Early stopping occurred at epoch 35 with best_epoch = 25 and best_val_0_accuracy = 0.5389


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:11:25,025] Trial 26 finished with value: 0.5389025389025389 and parameters: {'n_d': 47, 'n_a': 33, 'n_steps': 4, 'gamma': 1.5016836658551211, 'lambda_sparse': 0.007054679912539534, 'lr': 0.006313067878773272, 'mask_type': 'entmax'}. Best is trial 23 with value: 0.5421785421785422.



Early stopping occurred at epoch 10 with best_epoch = 0 and best_val_0_accuracy = 0.51761


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:11:31,199] Trial 27 finished with value: 0.5176085176085176 and parameters: {'n_d': 56, 'n_a': 32, 'n_steps': 4, 'gamma': 1.5008291954401394, 'lambda_sparse': 0.0058060673924064206, 'lr': 0.003920955641067566, 'mask_type': 'entmax'}. Best is trial 23 with value: 0.5421785421785422.



Early stopping occurred at epoch 10 with best_epoch = 0 and best_val_0_accuracy = 0.48239


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:11:35,751] Trial 28 finished with value: 0.4823914823914824 and parameters: {'n_d': 50, 'n_a': 24, 'n_steps': 3, 'gamma': 1.344106395567901, 'lambda_sparse': 0.0325356197480173, 'lr': 0.002712782428417435, 'mask_type': 'entmax'}. Best is trial 23 with value: 0.5421785421785422.



Early stopping occurred at epoch 15 with best_epoch = 5 and best_val_0_accuracy = 0.51761


C:\Users\campus4D044\anaconda3\Lib\site-packages\pytorch_tabnet\callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
[I 2025-07-17 10:11:43,271] Trial 29 finished with value: 0.5176085176085176 and parameters: {'n_d': 60, 'n_a': 35, 'n_steps': 3, 'gamma': 1.2344165823159132, 'lambda_sparse': 0.007037090439770757, 'lr': 0.015443501807953204, 'mask_type': 'entmax'}. Best is trial 23 with value: 0.5421785421785422.


Best params: {'n_d': 35, 'n_a': 32, 'n_steps': 3, 'gamma': 1.7029645287311754, 'lambda_sparse': 0.0013760855886573039, 'lr': 0.013960560634170088, 'mask_type': 'entmax'}
Best accuracy: 0.5421785421785422


In [172]:
best_params = study.best_params
best_params["optimizer_params"] = dict(lr=best_params["lr"])
del best_params["lr"]

In [34]:
print(list(x.columns))

['환율', '달러', '시장', '미국', '하락', '경제', '중국', '대비', '전망', '금리', '기록', '투자', '지수', '외국인', '금융', '가격', '코스피', '예상', '증가', '이날', '수출', '증시', '기업', '거래', '기준', '정부', '실적', '한국', '영향', '글로벌', '일본', '매수', '상황', '경기', '수준', '인상', '마감', '외환', '확대', '정책', '성장', '강세', '물가', '종목', '가능성', '통화', '약세', '기관', '가능', '가치', '지속', '주식', '포인트', '감소', '연구원', '해외', '원화', '위기', '개선', '서울', '주가', '위안화', '유지', '세계', '이익', '전년', '은행', '규모', '회복', '대통령', '설명', '매출', '개인', '판매', '이데일리', '최대', '엔화', '추가', '완화', '자금', '업종', '삼성전자', '전일', '인하', '내년', '코스닥', '수익', '수요', '자산', '급등', '거래일', '상승세', '변동', '무역', '영업', '시작', '달러화', '조정', '상품']


In [110]:
test_news=pd.read_excel('./data/test_news/NewsResult_20250701-20250704.xlsx')[['뉴스 식별자','일자','키워드','특성추출(가중치순 상위 50개)','본문']]

C:\Users\campus4D044\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")


In [116]:
test_news['날짜']=pd.to_datetime(test_news['일자'],format='%Y%m%d')

In [118]:
test_news=test_news[['날짜','키워드']]

In [121]:
test_df=pd.DataFrame({'date':test_news['날짜'],'keywords':test_news['키워드']})
test_df['keyword_list']=test_df['keywords'].apply(lambda x: x.split(','))
test_daily_keywords=test_df.groupby('date')['keyword_list'].apply(lambda lists: ' '.join(sum(lists, []))).reset_index()
test_tfidf_matrix=vectorizer.transform(test_daily_keywords['keyword_list'])
test_tfidf_df=pd.DataFrame(test_tfidf_matrix.toarray(),columns=terms)
test_tfidf_df['date']=test_daily_keywords['date']

In [125]:
test_tfidf_df['날짜']=pd.to_datetime(test_tfidf_df['date'])

In [126]:
test_tfidf_df=test_tfidf_df.drop('date',axis=1)

In [128]:
test_merged=pd.merge(test_tfidf_df,ex_rate,on='날짜',how='inner')

In [130]:
test_merged['변화율']=test_merged['원/달러(종가 15:30)'].pct_change().shift(-1)
test_merged['상승']=(test_merged['변화율']>0).astype(int)

In [143]:
test_merged=test_merged.dropna()

In [150]:
test_x=test_merged.drop(['날짜','상승','원/달러(종가 15:30)','변화율'],axis=1)
test_y=test_merged['상승']

In [151]:
pred_y=model.predict(test_x)>0.5
print(accuracy_score(test_y,pred_y))
print(f1_score(test_y,pred_y))

0.6666666666666666
0.8


In [152]:
pred_y

array([False,  True,  True])

In [153]:
test_y

0    1
1    1
2    1
Name: 상승, dtype: int32

In [308]:
top1000=[kw for kw, _ in Counter(all_keywords).most_common(70)]

In [309]:
from sklearn.feature_extraction.text import CountVectorizer

In [310]:
daily_keywords=df.groupby('date')['keyword_list'].apply(lambda lists: ' '.join(sum(lists,[]))).reset_index()

In [311]:
vectorizer=CountVectorizer(vocabulary=top1000)

In [312]:
count_matrix=vectorizer.fit_transform(daily_keywords['keyword_list'])

In [313]:
terms=vectorizer.get_feature_names_out()
count_df=pd.DataFrame(count_matrix.toarray())

In [314]:
count_df['date']=daily_keywords['date']

In [315]:
top_keywords_per_day=[]
for i, row in count_df.drop(columns='date').iterrows():
    top_terms=row.sort_values(ascending=False).head(10)
    for term, freq in top_terms.items():
        top_keywords_per_day.append({'date':count_df.loc[i,'date'],'keyword':term,'frequency':freq})

top_df=pd.DataFrame(top_keywords_per_day)

In [316]:
print(top_df)

            date  keyword  frequency
0     2009-01-01        6        793
1     2009-01-01       58        484
2     2009-01-01        9        442
3     2009-01-01        0        417
4     2009-01-01       26        401
...          ...      ...        ...
60245 2025-06-30        4        253
60246 2025-06-30        1        226
60247 2025-06-30       34        215
60248 2025-06-30        2        182
60249 2025-06-30       13        174

[60250 rows x 3 columns]


In [317]:
count_df['날짜']=count_df['date']
count_df=count_df.drop('date',axis=1)

In [318]:
ex_rate=pd.read_csv('./data/원화의 대미달러, 원화의 대위안_대엔 환율_10093253.csv')[['날짜','원/달러(종가 15:30)']]

In [319]:
ex_rate['날짜']=pd.to_datetime(ex_rate['날짜'])
ex_rate['원/달러(종가 15:30)']=ex_rate['원/달러(종가 15:30)'].str.replace(',','').astype(float)

In [320]:
merged_data=pd.merge(count_df,ex_rate,on='날짜',how='inner')

In [321]:
merged_data['변화율']=merged_data['원/달러(종가 15:30)'].pct_change().shift(-1)
merged_data['상승']=(merged_data['변화율']>0).astype(int)

C:\Users\campus4D044\AppData\Local\Temp\ipykernel_4352\2563095799.py:1: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  merged_data['변화율']=merged_data['원/달러(종가 15:30)'].pct_change().shift(-1)


In [322]:
merged_data['원/달러 shift-1']=merged_data['원/달러(종가 15:30)'].shift(-1)
merged_data['차이']=merged_data['원/달러 shift-1']-merged_data['원/달러(종가 15:30)']
#merged_data=merged_data[(merged_data['차이']>=5)|(merged_data['차이']<=-5)]

In [323]:
merged_data['category']=merged_data['차이'].apply(lambda x: 0 if x<-5 else (1 if -5 <= x < 5 else 2))

In [324]:
x=merged_data.drop(['날짜','상승','원/달러(종가 15:30)','변화율','원/달러 shift-1','차이','category'],axis=1) #
y=merged_data[['category']]

In [325]:
from sklearn.model_selection import train_test_split

In [326]:
tr_x,tt_x,tr_y,tt_y=train_test_split(x,y,train_size=0.7,shuffle=False,random_state=10)

In [327]:
from sklearn.preprocessing import StandardScaler

In [328]:
ss=StandardScaler()
tr_x=ss.fit_transform(tr_x)
tt_x=ss.transform(tt_x)

In [329]:
from sklearn.ensemble import RandomForestClassifier

In [330]:
model=RandomForestClassifier().fit(tr_x,tr_y)

C:\Users\campus4D044\anaconda3\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


In [331]:
pred_y=model.predict(tt_x)

In [332]:
from sklearn.metrics import accuracy_score,f1_score,confusion_matrix

In [333]:
print(accuracy_score(tt_y,pred_y))
print(f1_score(tt_y,pred_y,average='weighted'))
print(confusion_matrix(tt_y,pred_y))

0.600326264274062
0.47090899926646407
[[  2 212   5]
 [  7 724   9]
 [  3 254  10]]


In [334]:
from xgboost import XGBClassifier

In [335]:
model=XGBClassifier(random_state=10).fit(tr_x,tr_y)

In [336]:
pred_y=model.predict(tt_x)

In [337]:
print(accuracy_score(tt_y,pred_y))
print(f1_score(tt_y,pred_y,average='weighted'))
print(confusion_matrix(tt_y,pred_y))

0.5709624796084829
0.4849063191509954
[[ 14 182  23]
 [ 31 665  44]
 [ 13 233  21]]


In [338]:
from lightgbm import LGBMClassifier

In [339]:
model=LGBMClassifier(random_state=10).fit(tr_x,tr_y)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002592 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14970
[LightGBM] [Info] Number of data points in the train set: 2858, number of used features: 70
[LightGBM] [Info] Start training from score -1.666308
[LightGBM] [Info] Start training from score -0.491650
[LightGBM] [Info] Start training from score -1.612241


C:\Users\campus4D044\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:97: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\campus4D044\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


In [340]:
pred_y=model.predict(tt_x)

In [341]:
print(accuracy_score(tt_y,pred_y))
print(f1_score(tt_y,pred_y,average='weighted'))
print(confusion_matrix(tt_y,pred_y))

0.566884176182708
0.4881182607271266
[[ 12 184  23]
 [ 28 653  59]
 [ 14 223  30]]


In [342]:
from catboost import CatBoostClassifier

In [343]:
model=CatBoostClassifier().fit(tr_x,tr_y)

Learning rate set to 0.08348
0:	learn: 1.0699317	total: 29ms	remaining: 29s
1:	learn: 1.0463915	total: 44.5ms	remaining: 22.2s
2:	learn: 1.0261521	total: 60.3ms	remaining: 20s
3:	learn: 1.0090897	total: 75.7ms	remaining: 18.8s
4:	learn: 0.9955054	total: 93.3ms	remaining: 18.6s
5:	learn: 0.9817075	total: 109ms	remaining: 18.1s
6:	learn: 0.9710240	total: 126ms	remaining: 17.9s
7:	learn: 0.9614552	total: 142ms	remaining: 17.6s
8:	learn: 0.9536362	total: 157ms	remaining: 17.3s
9:	learn: 0.9471939	total: 172ms	remaining: 17s
10:	learn: 0.9407989	total: 187ms	remaining: 16.8s
11:	learn: 0.9351806	total: 203ms	remaining: 16.7s
12:	learn: 0.9303954	total: 218ms	remaining: 16.5s
13:	learn: 0.9260233	total: 233ms	remaining: 16.4s
14:	learn: 0.9215579	total: 248ms	remaining: 16.3s
15:	learn: 0.9178426	total: 263ms	remaining: 16.2s
16:	learn: 0.9147629	total: 278ms	remaining: 16.1s
17:	learn: 0.9111604	total: 293ms	remaining: 16s
18:	learn: 0.9082186	total: 308ms	remaining: 15.9s
19:	learn: 0.9052

In [344]:
pred_y=model.predict(tt_x)

In [345]:
print(accuracy_score(tt_y,pred_y))
print(f1_score(tt_y,pred_y,average='weighted'))
print(confusion_matrix(tt_y,pred_y))

0.5929853181076672
0.4835058263933832
[[  7 200  12]
 [ 14 703  23]
 [  8 242  17]]


In [646]:
news_df=pd.DataFrame({'date':news_data['일자'],'keywords':news_data['키워드']})

In [645]:
fx_df=pd.DataFrame({'date':ex_rate['날짜'],'exchange_rate':ex_rate['원/달러(종가 15:30)']})

In [ ]:
import pandas as pd
from collections import Counter
from datetime import timedelta

# 1. 뉴스 데이터 전처리: 날짜별 키워드 리스트 만들기
news_df['date'] = pd.to_datetime(news_df['date'])
news_df['keyword_list'] = news_df['keywords'].apply(lambda x: x.split(','))

# 2. 환율 데이터 전처리: 변동률 계산 후 급등/급락 구간 라벨링
fx_df['date'] = pd.to_datetime(fx_df['date'])
fx_df['change_pct'] = fx_df['exchange_rate'].pct_change()
fx_df['fx_label'] = fx_df['change_pct'].apply(lambda x: '상승' if x > 0.01 else ('하락' if x < -0.01 else '보합'))

# 3. 환율 변화와 뉴스 데이터를 병합
merged = pd.merge(news_df, fx_df[['date', 'fx_label']], on='date', how='inner')

# 4. 그룹별 키워드 빈도 계산 함수
def get_top_keywords(group_df, top_n=20):
    all_keywords = sum(group_df['keyword_list'], [])  # 리스트 합치기
    keyword_counts = Counter(all_keywords)
    return keyword_counts.most_common(top_n)

# 5. fx_label별 주요 키워드 추출
result = {}
for label in ['상승', '하락', '보합']:
    group_df = merged[merged['fx_label'] == label]
    result[label] = get_top_keywords(group_df, top_n=30)

# 6. 결과 출력
for label, keywords in result.items():
    print(f"\n📈 [{label} 구간] 상위 키워드")
    for word, freq in keywords:
        print(f"{word}: {freq}")

C:\Users\campus4D044\AppData\Local\Temp\ipykernel_6988\372705734.py:11: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  fx_df['change_pct'] = fx_df['exchange_rate'].pct_change()
